# Generated by Django 3.2.18 on 2023-05-02 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_resource', '0002_auto_20230413_2049'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartidaFallingObjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('time', models.IntegerField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_resource.playeruser')),
            ],
        ),
        migrations.CreateModel(
            name='PartidaEncontrarDiferencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maxtime', models.IntegerField()),
                ('n_objects', models.IntegerField()),
                ('time', models.IntegerField()),
                ('found_objects', models.IntegerField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_resource.playeruser')),
            ],
        ),
    ]
