# Generated by Django 3.2.18 on 2023-05-02 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_resource', '0003_partidaencontrardiferencias_partidafallingobjects'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partidaencontrardiferencias',
            old_name='time',
            new_name='time_taken',
        ),
        migrations.RenameField(
            model_name='partidafallingobjects',
            old_name='time',
            new_name='time_taken',
        ),
    ]
