# Generated by Django 3.2.18 on 2023-05-03 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_resource', '0004_auto_20230502_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partidafallingobjects',
            name='time_taken',
            field=models.FloatField(),
        ),
    ]
